name: Deploy to Firebase (prod)
"on": workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v16.4.0"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
        env:
          REACT_APP_NETWORK_NAME: "xdai"
          REACT_APP_NETWORK_COLOR: "#f6c343"
          REACT_APP_USE_GSN: true
          REACT_APP_GRAPHQL_ENDPOINT: "${{ secrets.XDAI_SUBGRAPH_URL }}"
          REACT_APP_GRAPHQL_ENDPOINT_MAINNET: "${{ secrets.MAINNET_SUBGRAPH_URL }}"
          REACT_APP_SUPABASE_KEY: "${{ secrets.SUPABASE_KEY }}"
          REACT_APP_SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
          REACT_APP_COPY_WORD: "${{ secrets.COPY_WORD }}"
          REACT_APP_PAYMASTER_ADDRESS: "0x9e59Ea5333cD4f402dAc320a04fafA023fe3810D"
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod
        env:
          GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
